untuk tengok documentation
sebelum square()
press 
shift + tab

In [1]:
# handle missing data - step 4
# import new dataset
import pandas as pd
dataset = pd.read_csv('10_initial_m.csv')
dataset.head()

country   Age  Weight  Sleep before 10pm
0        China  39.0    33.0               True
1  Philippines  49.0    47.0              False
2        China   NaN    39.0              False
3        China  39.0    78.0              False
4        China  29.0     NaN              False

In [2]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   country            10 non-null     object 
 1   Age                8 non-null      float64
 2   Weight             8 non-null      float64
 3   Sleep before 10pm  10 non-null     bool   
dtypes: bool(1), float64(2), object(1)
memory usage: 378.0+ bytes


In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [4]:
# #using SimpleImputer class 
# import numpy as np 
# # Importing the SimpleImputer class 
# from sklearn.impute import SimpleImputer 
  
# # Imputer object using the mean strategy and missing_values type for imputation 
# imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')
# X[:,1:3]= imputer.fit_transform(X[:,1:3]) # column index 1,2 (3 not included) : age & weight column
# X

In [5]:
#using SimpleImputer class 
import numpy as np 
# Importing the SimpleImputer class 
from sklearn.impute import SimpleImputer 
  
# Imputer object using the mean strategy and missing_values type for imputation 
imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')
imputer = imputer.fit(X[:,1:3]) # column index 1,2 (3 not included) : age & weight column
X[:,1:3]=imputer.transform(X[:,1:3]) # update 1,2 column

In [6]:
X

array([['China', 39.0, 33.0],
       ['Philippines', 49.0, 47.0],
       ['China', 36.25, 39.0],
       ['China', 39.0, 78.0],
       ['China', 29.0, 51.625],
       ['Indonesia', 34.0, 93.0],
       ['Philippines', 33.0, 57.0],
       ['Philippines', 26.0, 31.0],
       ['China', 36.25, 35.0],
       ['China', 41.0, 51.625]], dtype=object)

In [7]:
dataset # masih original ada nan sbb kita touch X= BUKAN dataset=

country   Age  Weight  Sleep before 10pm
0        China  39.0    33.0               True
1  Philippines  49.0    47.0              False
2        China   NaN    39.0              False
3        China  39.0    78.0              False
4        China  29.0     NaN              False
5    Indonesia  34.0    93.0              False
6  Philippines  33.0    57.0              False
7  Philippines  26.0    31.0               True
8        China   NaN    35.0               True
9        China  41.0     NaN              False

In [8]:
# kalau nak update dataset, terpulang
#to update the current dataset with filled NaN value
#please take note that you have change the original dataset
dataset.loc[:, 'Age'] = X[:,1]
dataset.loc[:, 'Weight'] = X[:,2]
dataset

country    Age  Weight  Sleep before 10pm
0        China   39.0    33.0               True
1  Philippines   49.0    47.0              False
2        China  36.25    39.0              False
3        China   39.0    78.0              False
4        China   29.0  51.625              False
5    Indonesia   34.0    93.0              False
6  Philippines   33.0    57.0              False
7  Philippines   26.0    31.0               True
8        China  36.25    35.0               True
9        China   41.0  51.625              False

In [9]:
# set is to get unique data, then make it into list followed by sort
d=list(set(dataset.iloc[:,0].values))
d.sort
d

['Philippines', 'China', 'Indonesia']

## handling categorical column

### a) Label Encoder

In [10]:
#handling categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 39.0, 33.0],
       [2, 49.0, 47.0],
       [0, 36.25, 39.0],
       [0, 39.0, 78.0],
       [0, 29.0, 51.625],
       [1, 34.0, 93.0],
       [2, 33.0, 57.0],
       [2, 26.0, 31.0],
       [0, 36.25, 35.0],
       [0, 41.0, 51.625]], dtype=object)

TO INVERSE back to categorical name

In [11]:
# inverse n convert to int type
labelencoder_X.inverse_transform(X[:,0].astype(int))

array(['China', 'Philippines', 'China', 'China', 'China', 'Indonesia',
       'Philippines', 'Philippines', 'China', 'China'], dtype=object)

In [12]:
# inverse n in list format
labelencoder_X.inverse_transform(X[:,0].tolist())

array(['China', 'Philippines', 'China', 'China', 'China', 'Indonesia',
       'Philippines', 'Philippines', 'China', 'China'], dtype=object)

In [13]:
labelencoder_X.inverse_transform([0, 2, 0, 0, 0, 1, 2, 2, 0, 0])

array(['China', 'Philippines', 'China', 'China', 'China', 'Indonesia',
       'Philippines', 'Philippines', 'China', 'China'], dtype=object)

In [20]:
labelencoder_X.inverse_transform([0,1,2])

array(['China', 'Indonesia', 'Philippines'], dtype=object)

In [21]:
labelencoder_X.inverse_transform([0])

array(['China'], dtype=object)

### b) OneHotEncoder

In [14]:
# one hot encoder
# be careful dont run 2 times hot encoder, if run 2x, column akan berganda tambah 
# remainder = 'passthrough' kalau xletak, ye akan delete column yang xbuat onehot encoder
# remainder = 'passthrough' kalau xletak, column yang xinvolve onehotencoder akan delete
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# at country column, at index 0, remainder = 'passthrough' for the rest columns yg xterlibat tidak didelete sekali
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough') 
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, 39.0, 33.0],
       [0.0, 0.0, 1.0, 49.0, 47.0],
       [1.0, 0.0, 0.0, 36.25, 39.0],
       [1.0, 0.0, 0.0, 39.0, 78.0],
       [1.0, 0.0, 0.0, 29.0, 51.625],
       [0.0, 1.0, 0.0, 34.0, 93.0],
       [0.0, 0.0, 1.0, 33.0, 57.0],
       [0.0, 0.0, 1.0, 26.0, 31.0],
       [1.0, 0.0, 0.0, 36.25, 35.0],
       [1.0, 0.0, 0.0, 41.0, 51.625]], dtype=object)

In [29]:
# # one hot encoder
# # be careful dont run 2 times hot encoder, if run 2x, column akan berganda tambah 
# # remainder = 'passthrough' kalau xletak, ye akan delete column yang xbuat onehot encoder
# # remainder = 'passthrough' kalau xletak, column yang xinvolve onehotencoder akan delete
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# # at country column, at index 0, remainder = 'passthrough' for the rest columns yg xterlibat tidak didelete sekali
# ct = ColumnTransformer([("test", OneHotEncoder(), [0])], remainder = 'passthrough') 
# z = ct.fit_transform(X)
# a=pd.DataFrame(z)
# a.head()
# # a=pd.DataFrame(z).head()

0    1    2    3      4       5
0  0.0  1.0  0.0  0.0   39.0    33.0
1  1.0  0.0  0.0  1.0   49.0    47.0
2  0.0  1.0  0.0  0.0  36.25    39.0
3  0.0  1.0  0.0  0.0   39.0    78.0
4  0.0  1.0  0.0  0.0   29.0  51.625

In [15]:
# split pg 108

In [16]:
# Dividing data into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

In [17]:
print(X_train)
print(y_train)

[[1.0 0.0 0.0 29.0 51.625]
 [1.0 0.0 0.0 41.0 51.625]
 [0.0 0.0 1.0 49.0 47.0]
 [0.0 0.0 1.0 33.0 57.0]
 [0.0 0.0 1.0 26.0 31.0]
 [1.0 0.0 0.0 39.0 78.0]
 [1.0 0.0 0.0 39.0 33.0]
 [0.0 1.0 0.0 34.0 93.0]]
[False False False False  True False  True False]


In [18]:
print(X_test)

[[1.0 0.0 0.0 36.25 39.0]
 [1.0 0.0 0.0 36.25 35.0]]


In [19]:
# xperlu
#Exercise
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[1 0 0 0 0 0 0 1 1 0]
