# 4. numpy library

In [1]:
#import numpy library
import numpy as np

In [2]:
#Create an array
X=np.array([1,2,3])
X

array([1, 2, 3])

In [3]:
#Check dimension of an array
X.ndim

1

In [4]:
#Check shape of an array
X.shape

(3,)

In [5]:
#Check size of an array
X.size

3

In [6]:
#Check data type of an array
X.dtype

dtype('int32')

In [7]:
#Read the first element in an array
X[0]

1

In [15]:
# Read the first element in an array:
X[0,]

1

In [8]:
#Read only the first two elements
X[:2]

array([1, 2])

In [16]:
#Save the array: SAVE first then load
np.save('nama',X)

In [17]:
#Load the array
np.load("nama.npy")

array([1, 2, 3])

## exercise

In [11]:
#Exercise pg 71
#Create 2D array
Y=np.array([[1,2,3],[4,5,6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#read the entry(1,2) from the array
Y[1,2]

6

In [13]:
print(Y.dtype)
print(Y.size)
print(Y.ndim)
print(Y.shape)

int32
6
2
(2, 3)


In [14]:
#import numpy library
import numpy as np
#Create an array
X=np.array([1,2,3])
X
#Check dimension of an array
X.ndim
#Check shape of an array
X.shape
#Check size of an array
X.size
#Check data type of an array
X.dtype
#Read the first element in an array
X[0]
#Read only the first two elements
X[:2]
#Load the array
np.load("X.npy")
#Save the array:
np.save('X',X)
#Exercise
#Create an array
Y=np.array([[1,2,3],[4,5,6]])
Y
#read the entry(1,2) from the array
Y[1,2]
print(Y.dtype)
print(Y.size)
print(Y.ndim)
print(Y.shape)

int32
6
2
(2, 3)
