In [4]:
import pandas as pd
dataset = pd.read_csv('dataset/10_initial_m.csv')
dataset.head()

country   Age  Weight  Sleep before 10pm
0        China  39.0    33.0               True
1  Philippines  49.0    47.0              False
2        China   NaN    39.0              False
3        China  39.0    78.0              False
4        China  29.0     NaN              False

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   country            10 non-null     object 
 1   Age                8 non-null      float64
 2   Weight             8 non-null      float64
 3   Sleep before 10pm  10 non-null     bool   
dtypes: bool(1), float64(2), object(1)
memory usage: 378.0+ bytes


In [6]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [7]:
#using SimpleImputer class 
import numpy as np 
# Importing the SimpleImputer class 
from sklearn.impute import SimpleImputer 
  
# Imputer object using the mean strategy and missing_values type for imputation 
imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')
imputer = imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [8]:
x

array([['China', 39.0, 33.0],
       ['Philippines', 49.0, 47.0],
       ['China', 36.25, 39.0],
       ['China', 39.0, 78.0],
       ['China', 29.0, 51.625],
       ['Indonesia', 34.0, 93.0],
       ['Philippines', 33.0, 57.0],
       ['Philippines', 26.0, 31.0],
       ['China', 36.25, 35.0],
       ['China', 41.0, 51.625]], dtype=object)

In [9]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [10]:
#to update the current dataset with filled NaN value
#please take note that you have change the original dataset
dataset.loc[:, 'Age'] = x[:,1]
dataset.loc[:, 'Weight'] = x[:,2]
dataset

country   Age Weight  Sleep before 10pm
0        China  39.0   33.0               True
1  Philippines  49.0   47.0              False
2        China   NaN   39.0              False
3        China  39.0   78.0              False
4        China  29.0    NaN              False
5    Indonesia  34.0   93.0              False
6  Philippines  33.0   57.0              False
7  Philippines  26.0   31.0               True
8        China   NaN   35.0               True
9        China  41.0    NaN              False

In [11]:
dataset.info

<bound method DataFrame.info of        country   Age Weight  Sleep before 10pm
0        China  39.0   33.0               True
1  Philippines  49.0   47.0              False
2        China   NaN   39.0              False
3        China  39.0   78.0              False
4        China  29.0    NaN              False
5    Indonesia  34.0   93.0              False
6  Philippines  33.0   57.0              False
7  Philippines  26.0   31.0               True
8        China   NaN   35.0               True
9        China  41.0    NaN              False>

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   country            10 non-null     object
 1   Age                8 non-null      object
 2   Weight             8 non-null      object
 3   Sleep before 10pm  10 non-null     bool  
dtypes: bool(1), object(3)
memory usage: 378.0+ bytes


In [ ]:
x.info()

In [13]:
#handling categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
x

array([[0, 39.0, 33.0],
       [2, 49.0, 47.0],
       [0, nan, 39.0],
       [0, 39.0, 78.0],
       [0, 29.0, nan],
       [1, 34.0, 93.0],
       [2, 33.0, 57.0],
       [2, 26.0, 31.0],
       [0, nan, 35.0],
       [0, 41.0, nan]], dtype=object)

In [14]:
labelencoder_x.inverse_transform([0, 2, 0, 0, 0, 1, 2, 2, 0, 0])

array(['China', 'Philippines', 'China', 'China', 'China', 'Indonesia',
       'Philippines', 'Philippines', 'China', 'China'], dtype=object)

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)
x

array([[0.0, 1.0, 0.0, 0.0, 39.0, 33.0],
       [1.0, 0.0, 0.0, 1.0, 49.0, 47.0],
       [0.0, 1.0, 0.0, 0.0, nan, 39.0],
       [0.0, 1.0, 0.0, 0.0, 39.0, 78.0],
       [0.0, 1.0, 0.0, 0.0, 29.0, nan],
       [1.0, 0.0, 1.0, 0.0, 34.0, 93.0],
       [1.0, 0.0, 0.0, 1.0, 33.0, 57.0],
       [1.0, 0.0, 0.0, 1.0, 26.0, 31.0],
       [0.0, 1.0, 0.0, 0.0, nan, 35.0],
       [0.0, 1.0, 0.0, 0.0, 41.0, nan]], dtype=object)

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state=0)

In [25]:
print(x_train)
print(y_train)

[[0.0 1.0 0.0 0.0 29.0 nan]
 [0.0 1.0 0.0 0.0 41.0 nan]
 [1.0 0.0 0.0 1.0 49.0 47.0]
 [1.0 0.0 0.0 1.0 33.0 57.0]
 [1.0 0.0 0.0 1.0 26.0 31.0]
 [0.0 1.0 0.0 0.0 39.0 78.0]
 [0.0 1.0 0.0 0.0 39.0 33.0]
 [1.0 0.0 1.0 0.0 34.0 93.0]]
[False False False False  True False  True False]


In [26]:
#Exercise
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[1 0 0 0 0 0 0 1 1 0]


In [28]:
print(x_train)
print(y_train)

[[0.0 1.0 0.0 0.0 29.0 nan]
 [0.0 1.0 0.0 0.0 41.0 nan]
 [1.0 0.0 0.0 1.0 49.0 47.0]
 [1.0 0.0 0.0 1.0 33.0 57.0]
 [1.0 0.0 0.0 1.0 26.0 31.0]
 [0.0 1.0 0.0 0.0 39.0 78.0]
 [0.0 1.0 0.0 0.0 39.0 33.0]
 [1.0 0.0 1.0 0.0 34.0 93.0]]
[False False False False  True False  True False]


In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state=0)

In [30]:
print(x_train)
print(y_train)

[[0.0 1.0 0.0 0.0 29.0 nan]
 [0.0 1.0 0.0 0.0 41.0 nan]
 [1.0 0.0 0.0 1.0 49.0 47.0]
 [1.0 0.0 0.0 1.0 33.0 57.0]
 [1.0 0.0 0.0 1.0 26.0 31.0]
 [0.0 1.0 0.0 0.0 39.0 78.0]
 [0.0 1.0 0.0 0.0 39.0 33.0]
 [1.0 0.0 1.0 0.0 34.0 93.0]]
[0 0 0 0 1 0 1 0]


In [31]:
print(x_test)

[[0.0 1.0 0.0 0.0 nan 39.0]
 [0.0 1.0 0.0 0.0 nan 35.0]]
