In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds=pd.read_csv('MLR_mix.csv')
ds.head()

S&P department (spend)  Admin department(spend)  \
0                  101184                    70674   
1                   70132                    52030   
2                  149539                    98535   
3                   75821                    53649   
4                   97730                    68667   

   Operation department(spend) state  Profit  
0                        97009     A  259480  
1                        63587     B  137019  
2                       199994     A  495552  
3                        66500     B  165057  
4                        91754     B  247841

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   S&P department (spend)       50 non-null     int64 
 1   Admin department(spend)      50 non-null     int64 
 2   Operation department(spend)  50 non-null     int64 
 3   state                        50 non-null     object
 4   Profit                       50 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 2.1+ KB


In [4]:
#x=ds.iloc[:,:-1].values #Volume
#x=ds.iloc[:,0:3].values #Volume
#x=ds.iloc[:,[0,1,2,3]].values 
#y=ds.iloc[:,4].values #Price
#=ds.iloc[:,-1].values #Volume
#print(x)
#print(y)

In [5]:
x=ds.iloc[:,[0,1,2,3]].values 
y=ds.iloc[:,4].values

In [6]:
#Handling or Encode categorical variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x = LabelEncoder()
x[:, 3] = labelencoder_x.fit_transform(x[:, 3])

ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)
print(x)

[[1.0 0.0 101184 70674 97009]
 [0.0 1.0 70132 52030 63587]
 [1.0 0.0 149539 98535 199994]
 [0.0 1.0 75821 53649 66500]
 [0.0 1.0 97730 68667 91754]
 [0.0 1.0 84544 60923 81618]
 [1.0 0.0 117490 85379 146277]
 [0.0 1.0 119913 86499 150579]
 [0.0 1.0 145244 95108 189066]
 [1.0 0.0 147217 95598 190309]
 [0.0 1.0 81746 56815 72351]
 [1.0 0.0 107967 74058 106215]
 [1.0 0.0 74692 52493 64267]
 [1.0 0.0 72228 52210 63719]
 [0.0 1.0 96292 68521 90007]
 [1.0 0.0 124506 86995 153382]
 [0.0 1.0 113543 82796 122345]
 [1.0 0.0 142585 94589 184603]
 [1.0 0.0 118057 86227 146948]
 [1.0 0.0 86260 63082 85320]
 [1.0 0.0 63601 51026 59932]
 [1.0 0.0 113200 76388 115984]
 [0.0 1.0 141331 93725 171453]
 [1.0 0.0 79667 54864 69102]
 [0.0 1.0 112208 75407 115316]
 [1.0 0.0 82622 59754 72987]
 [0.0 1.0 127721 88888 153477]
 [0.0 1.0 117901 85532 146822]
 [0.0 1.0 147364 96275 191812]
 [1.0 0.0 110661 75404 114864]
 [0.0 1.0 107360 73604 100773]
 [0.0 1.0 87194 63403 87468]
 [1.0 0.0 75381 52575 66116]
 [1.0 

In [7]:
#Avoid dummy variable,remove the unnecessary column
x=x[:,1:] #keep B
#x=x[:,[0,2,3,4]] #keep A
print(x)

[[0.0 101184 70674 97009]
 [1.0 70132 52030 63587]
 [0.0 149539 98535 199994]
 [1.0 75821 53649 66500]
 [1.0 97730 68667 91754]
 [1.0 84544 60923 81618]
 [0.0 117490 85379 146277]
 [1.0 119913 86499 150579]
 [1.0 145244 95108 189066]
 [0.0 147217 95598 190309]
 [1.0 81746 56815 72351]
 [0.0 107967 74058 106215]
 [0.0 74692 52493 64267]
 [0.0 72228 52210 63719]
 [1.0 96292 68521 90007]
 [0.0 124506 86995 153382]
 [1.0 113543 82796 122345]
 [0.0 142585 94589 184603]
 [0.0 118057 86227 146948]
 [0.0 86260 63082 85320]
 [0.0 63601 51026 59932]
 [0.0 113200 76388 115984]
 [1.0 141331 93725 171453]
 [0.0 79667 54864 69102]
 [1.0 112208 75407 115316]
 [0.0 82622 59754 72987]
 [1.0 127721 88888 153477]
 [1.0 117901 85532 146822]
 [1.0 147364 96275 191812]
 [0.0 110661 75404 114864]
 [1.0 107360 73604 100773]
 [1.0 87194 63403 87468]
 [0.0 75381 52575 66116]
 [0.0 113427 78653 119763]
 [1.0 103004 71720 100065]
 [1.0 109249 74209 109578]
 [1.0 134157 92647 167690]
 [0.0 116481 83866 141719]
 [1

#calculate the correlation coefficient for the dataset
corr = ds.corr()
print(corr)

In [8]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [9]:
#import scaler
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)

In [10]:
# multiple linear regression - step 2 
#Fitting simple linear regression to training set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print('Coefficients,beta:', regressor.coef_)
print('Constant,alpha:', regressor.predict([[0,0,0,0]])) # y= mx1 + mx2 + mx3 + mx4 + c

Coefficients,beta: [ -3778.94266828  15057.72856866 102355.90072011  -7688.65481663]
Constant,alpha: [300828.1]


In [11]:
x_test = sc_X.transform(x_test)

In [3]:
#Predicting the results for test set
y_pred=regressor.predict(x_test)
print(y_pred) # predicted
print(y_test) # actual

NameError: name 'regressor' is not defined

In [13]:
#calculate the correlation coefficient
corr=np.corrcoef(y_pred, y_test)
print(corr)

[[1.         0.99542528]
 [0.99542528 1.        ]]


In [14]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test, y_pred)
print(MSE) # MSE to compare 2 model

114075328.33230352


In [15]:

# #Visualizing training set result
# plt.scatter(x_train,y_train,color='blue') # plot the points
# plt.plot(x_train, regressor.predict(x_train),color='red')# plot the line
# plt.title('Price vs Volume (Training set)')
# plt.xlabel('Volume')
# plt.ylabel('Price')

In [16]:
#df = 

In [17]:
x_input = sc_X.transform([[0,90020,55200,94230]])
y_pred=regressor.predict(x_input)
print(y_pred)

[174400.58019591]
