# Naive Bayes Classification

In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
#import dataset
ds=pd.read_csv('play.csv')
ds.head()

outlook temperature humidity  windy Play(Y/N)
0   Sunny         Hot     High  False        No
1   Sunny         Hot     High   True        No
2   Rainy        Mild     High  False       Yes
3   Rainy        Cool   Normal  False       Yes
4   Rainy        Cool   Normal   True        No

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   outlook      10 non-null     object
 1   temperature  10 non-null     object
 2   humidity     10 non-null     object
 3   windy        10 non-null     bool  
 4   Play(Y/N)    10 non-null     object
dtypes: bool(1), object(4)
memory usage: 458.0+ bytes


In [4]:
#x=ds.iloc[:,[0,1,2,3]].values  == x=ds.iloc[:,:-1].values
#x=ds.iloc[:,0:4].values  ==  x=ds.iloc[:,:-1].values
#x=ds.iloc[:,:4].values  ==  x=ds.iloc[:,:-1].values
x=ds.iloc[:,:-1].values
y=ds.iloc[:,4].values

In [5]:
pd.unique(ds['outlook'])

array(['Sunny', 'Rainy'], dtype=object)

In [6]:
#set is to get unique data, then make it into list follow by sort
#after sort, data in sequence 0,1,2
i=0
for i in range(0,4):
    d=list(set(ds.iloc[:, i].values))
    d.sort()
    print(i,d)
    i=i+1
    
# option 2
# pd.unique(ds['outlook'])

0 ['Rainy', 'Sunny']
1 ['Cool', 'Hot', 'Mild']
2 ['High', 'Normal']
3 [False, True]


In [7]:
#Handling or Encode categorical variables
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])
x[:, 2] = labelencoder_X.fit_transform(x[:, 2])
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
print(x)

[[1 1 0 0]
 [1 1 0 1]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 0]
 [1 0 1 0]
 [0 2 1 0]
 [1 2 1 1]
 [0 2 0 1]]


In [8]:
# split here

In [9]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [10]:
#fitting Naïve Bayes Classifier to the dataset 
from sklearn.naive_bayes import BernoulliNB
classifier= BernoulliNB()

classifier=classifier.fit(x_train,y_train)

In [11]:
#Predict the test set results
y_pred=classifier.predict(x_test)

In [12]:
#Making Confusion Matrix – to check whether the test set gives the correct result
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [2, 0]], dtype=int64)

In [13]:
#Predict using classifier
prediction=classifier.predict([[1, 0, 0, 0]])#sunny day,cool temperature, humidity high, windy false 
print(prediction)

['No']
