In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#import dataset
ds=pd.read_csv('LRT_car.csv')
ds.head()

Montly Salary  age  Y/N
0           2386   18    0
1           2486   19    0
2           2586   20    0
3           2686   20    0
4           2756   20    0

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Montly Salary  400 non-null    int64
 1   age            400 non-null    int64
 2   Y/N            400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [4]:
x=ds.iloc[:,:-1].values
y=ds.iloc[:,2].values

In [5]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [7]:
#fitting KNN classifier to the training set 
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)#using Euclidean distance
classifier.fit(x_train,y_train)
# Manhattan distance is calculated as the sum of the absolute differences between the two vectors
# Minkowski distance is a distance/ similarity measurement between two points in the normed vector space

KNeighborsClassifier()

In [8]:
#Predict the test set results
y_pred=classifier.predict(x_test)

In [9]:
y_test,y_pred

(array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64))

In [10]:
#Making Confusion Matrix – to check whether the test set gives the correct result
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [11]:
cm

array([[40,  2],
       [ 3, 35]], dtype=int64)

In [14]:
# Finding accuracy
from sklearn.metrics import accuracy_score
AR=accuracy_score(y_test,y_pred)
print(AR)

0.9375


In [15]:
xP=sc_x.transform([[6000,35]])
print(xP)

[[ 0.10412149 -0.49974943]]


In [16]:
y_pred_new=classifier.predict(xP)
print(y_pred_new)

[0]


In [17]:
# Predicting a value salary=15000 and age=21
y_pred_new=classifier.predict(sc_x.transform([[15000,21]]))
print(y_pred_new)

[1]
